baseURL = 'https://ozeloglu.io/'
languageCode = 'en-us'
title = "Gökhan's Blog"
theme = "tale"
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "resume"
    name = "Rèsume"
    title = "Rèsume"
    url = "/resume/"
    weight = 0
[Author]
    name = "Gökhan Özeloğlu"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'lovelace'
    tabWidth = 4